[DEFAULT]
debian-branch = debian/master
upstream-branch = upstream/master
pristine-tar = True

[import-ref]
upstream-tree = BRANCH
postimport = gbp dch --new-version=%(version)s --snapshot --auto -- debian

# vim: set syn=cfg:
